public class ExceptionHandling {
    public static void main(String[] args) {
        int a =5;
        int b =0;
        try {
            divide(a,b);
        } catch (ArithmeticException e) {
            System.err.println(e.getMessage());
        }
        finally{
            System.out.println("YOur work is done");
            
        }
    }

  static int divide(int a, int b) {
    if (b==0) {
        throw new ArithmeticException("pls dont give b as 0");
        
    }
    return a/b;
    }

}
